pub static ADJECTIVES: [&str; 237] = [
    "ambling", "axe-throwing", "beaming", "billowy", "blinking", "banjo-playing", "bouncy", "bounding",
    "breezy", "bubbling", "bubbly", "bumbling", "bumpy", "burbling", "bustling", "buttery",
    "candied", "capering", "cartwheeling", "cheerful", "chipper", "chomping", "chortling",
    "chubby", "chuckling", "carbon-based", "cloudy", "clumsy", "cosmic", "cozy", "crackling",
    "crumbly", "crunching", "cuddly", "curious", "curly", "custardy", "dabbling", "dainty",
    "dapper", "dappled", "dawdling", "daydreaming", "dewy", "dinky", "dizzy", "doodling",
    "doughy", "downy", "dreaming", "dreamy", "drifting", "drowsy", "earthy", "feathery",
    "ferny", "fizzling", "fizzing", "fizzy", "flapping", "flitting", "floating", "floaty",
    "fluffy", "fluttering", "foraging", "frilly", "fringed", "frizzy", "frolicking", "frosted",
    "frosty", "fuzzy", "gallivanting", "galloping", "gamboling", "gentle", "giddy", "giggling",
    "gingery", "gliding", "glittery", "gnawing", "gobbling", "goofy", "grinning", "gurgling",
    "herby", "hiccuping", "honeyed", "hopping", "hopscotching", "humble", "humming", "jammy",
    "jaunty", "jazzy", "jigging", "jiggly", "jolly", "jostling", "jouncing", "juggling",
    "lazing", "lanky", "leafy", "leaping", "lemony", "lollygagging", "lossy", "lunar",
    "meandering", "mellow", "merry", "mini", "minty", "misty", "moseying", "mossy", "munching",
    "mushy", "musing", "napping", "nibbling", "nifty", "nimble", "noshing", "ontological",
    "paddling", "peachy", "peeking", "panhandling", "peppery", "prickly", "perky", "pirouetting",
    "plodding", "plucky", "plummy", "plush", "pondering", "popping", "prancing", "pudgy",
    "puttering", "quirky", "rambling", "rampaging", "romping", "ruffled", "rummaging",
    "sauntering", "scampering", "scrambling", "scurrying", "scuttling", "shimmery",
    "shuffling", "silky", "simmering", "sipping", "skipping", "sleepy", "slurping", "snacking",
    "snazzy", "snickering", "sniffling", "snoozing", "snoring", "snowy", "skedaddling", "snug",
    "soaring", "somersaulting", "sparkly", "speckled", "spiffy", "splashing", "sploshing",
    "spotted", "sprightly", "sprinkled", "spry", "squelching", "squiggly", "squinting",
    "squishy", "starry", "stretching", "stripey", "stubby", "sugary", "sunny", "swaying",
    "swirly", "swooping", "syrupy", "tangy", "teeny", "teetering", "theologizing", "tiny", "tiptoeing",
    "toasty", "toddling", "tottering", "traipsing", "trotting", "trundling", "tubby", "tufted",
    "tumbling", "twinkly", "twirling", "vaulting", "velvety", "waddling", "waltzing",
    "wandering", "wee", "whimsical", "whistling", "wiggly", "wishing", "wispy", "witty",
    "wobbling", "wobbly", "woodsy", "woolgathering", "woolly", "yawning", "zany", "zappy",
    "zesty", "zippy",
];

pub static NOUNS: [&str; 247] = [
    "accordion", "acorn", "alpaca", "apricot", "axolotl", "badger", "bagel", "balloon",
    "bangle", "banjo", "barnacle", "bauble", "beanbag", "beaver", "beetle", "beret", "biscuit",
    "blossom", "bobbin", "bonnet", "brooch", "buckle", "bumblebee", "bunny", "butterfly",
    "button", "capybara", "caterpillar", "chameleon", "cherry", "chestnut", "chipmunk", "clog",
    "clover", "clownfish", "coaster", "cobbler", "colander", "conker", "cookie", "cricket",
    "crumble", "crumpet", "custard", "cuttlefish", "cygnet", "daisy", "dewdrop", "dodo",
    "doily", "domino", "donkey", "dormouse", "dove", "dragonfly", "dreidel", "duckling",
    "dugong", "dumpling", "earmuff", "earwig", "fawn", "ferret", "fez", "fiddle", "fig",
    "finch", "firefly", "flamingo", "flapjack", "fledgling", "foal", "fritter", "frog",
    "funnel", "galosh", "gecko", "gerbil", "glowworm", "gnocchi", "gobstopper", "godwit",
    "gosling", "gourd", "grape", "grasshopper", "guava", "gumdrop", "hammock", "hamster",
    "hare", "harmonica", "hazelnut", "hedgehog", "heron", "ibex", "iguana", "jellybean",
    "jellyfish", "joey", "kazoo", "kestrel", "kettle", "kite", "kitten", "kiwi", "kumquat",
    "ladle", "ladybug", "lamb", "lantern", "lark", "leek", "lemming", "lemur", "limpet",
    "llama", "locket", "lollipop", "lychee", "macaron", "magpie", "manatee", "mango", "marble",
    "marmot", "marshmallow", "mayfly", "meerkat", "melon", "mink", "mitten", "moccasin",
    "mole", "mongoose", "moth", "mudpuppy", "muffin", "muffler", "mushroom", "narwhal",
    "nautilus", "newt", "nun", "ocarina", "okapi", "olive", "otter", "owlet", "pancake",
    "pangolin", "pansy", "papaya", "parsnip", "peach", "pebble", "pecan", "pelican",
    "periwinkle", "persimmon", "piccolo", "pierogi", "piglet", "pillow", "pinecone",
    "pinwheel", "platypus", "pope", "plum", "pollywog", "pompom", "pony", "possum",
    "pretzel", "pudding", "pufferfish", "puffin", "pumpkin", "quail", "quilt", "quokka",
    "raccoon", "radish", "ravioli", "robin", "salamander", "samosa", "sandal", "sandpiper",
    "saucer", "scarf", "scone", "seahorse", "shallot", "shrew", "sieve", "skink", "slipper",
    "slug", "snail", "snipe", "snowflake", "sparrow", "spatula", "spool", "sprig", "sprout",
    "squash", "starfish", "starling", "stoat", "swallow", "tadpole", "tambourine", "tapir",
    "tassel", "teacup", "teapot", "terrapin", "thimble", "toad", "toadstool", "toggle",
    "tortoise", "toucan", "trifle", "trinket", "truffle", "tulip", "turban", "turnip",
    "turtle", "twig", "ukulele", "umbrella", "urchin", "vole", "waffle", "walnut", "walrus",
    "weasel", "whisk", "wombat", "wonton", "woodlouse", "wren", "xylophone",
];
