// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  State,
} from "./types";


export default __t.row({
  identity: __t.identity().primaryKey(),
  verified: __t.bool(),
  isHuman: __t.bool().name("is_human"),
  name: __t.string(),
  bestScoreMovect: __t.u32().name("best_score_movect"),
  bestScoreSingmaster: __t.string().name("best_score_singmaster"),
  distanceToSolve: __t.u64().name("distance_to_solve"),
  get state() {
    return State;
  },
});
