// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CornerPatternDatabase = __t.object("CornerPatternDatabase", {
  pdbIdentity: __t.identity(),
  get pdb() {
    return DbStorage;
  },
});
export type CornerPatternDatabase = __Infer<typeof CornerPatternDatabase>;

export const Cuber = __t.object("Cuber", {
  identity: __t.identity(),
  verified: __t.bool(),
  isHuman: __t.bool(),
  name: __t.string(),
  bestScoreMovect: __t.u32(),
  bestScoreSingmaster: __t.string(),
  distanceToSolve: __t.u64(),
  get state() {
    return State;
  },
});
export type Cuber = __Infer<typeof Cuber>;

export const DbStorage = __t.object("DbStorage", {
  store: __t.byteArray(),
});
export type DbStorage = __Infer<typeof DbStorage>;

export const State = __t.object("State", {
  cp: __t.byteArray(),
  co: __t.byteArray(),
});
export type State = __Infer<typeof State>;

