// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApplyMoveReducer from "../apply_move_reducer";
import SetDistanceToSolveReducer from "../set_distance_to_solve_reducer";
import SetHumanStatusReducer from "../set_human_status_reducer";
import SetNameReducer from "../set_name_reducer";
import SetVerifiedReducer from "../set_verified_reducer";
import TestAndSetBestScoreReducer from "../test_and_set_best_score_reducer";

export type ApplyMoveParams = __Infer<typeof ApplyMoveReducer>;
export type SetDistanceToSolveParams = __Infer<typeof SetDistanceToSolveReducer>;
export type SetHumanStatusParams = __Infer<typeof SetHumanStatusReducer>;
export type SetNameParams = __Infer<typeof SetNameReducer>;
export type SetVerifiedParams = __Infer<typeof SetVerifiedReducer>;
export type TestAndSetBestScoreParams = __Infer<typeof TestAndSetBestScoreReducer>;

